<!doctype html>
<html class="no-js" lang="en" id="home">
<head>
	<title>{{meta.title}}</title>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta property="og:title" content="Simon Pay - Web Designer &amp; Front-end Developer">
	<meta property="og:type" content="website">
	<meta property="og:url" content="http://www.simonpay.co.uk/">
	<meta property="og:image" content="http://www.simonpay.co.uk/images/simonpay-banner.jpg">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <meta name="description" content="{{meta.description}}">
    <meta name="keywords" content="{{meta.keywords}}">
	<meta name="robots" content="noodp,noydir">
	<meta name="author" content="Simon Pay">
	<meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE">
	<link href="/stylesheets/app.css" rel="stylesheet">
	<link rel="canonical" href="{{meta.canonical}}">
    <link rel="icon" type="image/ico" href="images/favicon.ico">
	<script>document.cookie='resolution='+Math.max(screen.width,screen.height)+'; path=/';</script>
	<!-- JavaScript -->
	<!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->
</head>
<body data-spy="scroll" data-target="#navbar" data-offset="50">

{{>body}}

</body>
</html>
